wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.10
    cli_version: 0.16.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1747584376.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.12.10
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
