name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.3.4
  - urllib3=1.24.1
  - notebook=7.3.2
  - ipython=9.1.0
  - seaborn=0.13.2
  - pandas=2.2.1
  - pip=23.3.1
  - ydata-profiling=4.10.0
  - pyarrow=14.0.2
  - pip:
    - wandb==0.16.4
    - ipywidgets=8.1.7
      
