_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 23
                - 55
                - 62
            "4": 3.12.9
            "5": 0.19.10
            "8":
                - 1
                - 5
            "12": 0.19.10
            "13": linux-x86_64
augmentations:
    value:
        crop_size: 224
        rot_angle: 45
batch_size:
    value: 128
weight_decay:
    value: 0.01
